### ISSUE TITLE
Allow working from global install

### ISSUE THREAD

**Issue by eddyc** [nwhetsell/csound-api#12]
It would be handy for csound-api to work from a global install npm install -g csound-api. Currently if installed globally when trying to require I get the error:
```
Error: Cannot find module 'csound-api'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at repl:1:16
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:536:10)
```

**Comment by nwhetsell** [comment]
I’m not sure that this is a csound-api issue. I have [Jasmine](https://jasmine.github.io/edge/node.html) installed globally and running `require('jasmine')` in a Node.js REPL produces the same result.

**Comment by eddyc** [comment]
That was a misunderstanding of how node worked on my part, for macOS I needed to set the NODE_PATH environmental variable, then I could require it fine, sorry for the noise.

**Comment by nwhetsell** [comment]
No worries!
